### ISSUE TITLE
Headings with anchor has no value

### ISSUE THREAD

**Issue by lanbau** [jammeryhq/gridsome-starter-articles#10]
hi this is an awesome starter!

i have H2 headings that are linked e.g 

```
## **[GrowthBar](https://chrome.google.com/webstore/detail/growthbar/obpnfefhfgcoodmdacdmeefknpkdekpn)**
```
However it is not appearing as the sidebar as the values of the headings processed by the transformer is ""

its fine when i remove the link

any idea where i should look to resolve this issue

**Comment by noxify** [comment]
Hi,

unfortunately I have no idea how to solve this.

In my examples I used "plain" headings without any external link

Maybe you have to extend the Sidebar component to be able to render it correctly.

https://github.com/jammeryhq/gridsome-starter-articles/blob/master/src/components/PageSidebar.vue


Since I stopped using Gridsome and can't give you more support than this.
Sorry!
